name: Automated Tests

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
          sudo apt-get install -y libopencv-dev
          sudo apt-get install -y libboost-all-dev

      - name: Configure CMake
        run: |
          cd Software/LMSourceCode
          cmake -B build -S .

      - name: Build
        run: |
          cd Software/LMSourceCode
          cmake --build build --config Release

      - name: Run Automated Tests
        run: |
          cd Software/LMSourceCode/build
          ./gs_automated_testing
        env:
          # Configure any environment variables needed for tests
          GS_TEST_SUITE_DIR: ${{ github.workspace }}/Software/LMSourceCode/test_suite