---
name: Automated Tests

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            /var/cache/apt/archives
            ~/.cache/pip
            Software/LMSourceCode/ImageProcessing/build
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/CMakeLists.txt', 'Software/LMSourceCode/ImageProcessing/**/*.h', 'Software/LMSourceCode/ImageProcessing/**/*.hpp') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake  ninja-build
          sudo apt-get install -y libopencv-dev
          sudo apt-get install -y libboost-all-dev
          sudo apt-get install -y pkg-config
          sudo apt-get install -y libavcodec-dev libavformat-dev libavutil-dev
          sudo apt-get install libcamera-tools gstreamer1.0-libcamera
          # Check if libcamera headers exist and create symlink if needed
          if [ ! -f /usr/include/libcamera/formats.h ]; then
            # Find where the headers might be located
            LIBCAMERA_FORMATS=$(find /usr -name formats.h | grep libcamera || true)
            if [ ! -z "$LIBCAMERA_FORMATS" ]; then
              LIBCAMERA_DIR=$(dirname $(dirname $LIBCAMERA_FORMATS))
              echo "Found libcamera headers at $LIBCAMERA_DIR"
              sudo ln -sf $LIBCAMERA_DIR /usr/include/libcamera
            else
              # If headers are not found, try to install from source
              echo "Could not find libcamera headers, installing from source"
              git clone https://git.libcamera.org/libcamera/libcamera.git
              cd libcamera
              meson build -Dpipelines=raspberrypi -Dipas=raspberrypi -Dv4l2=true
              ninja -C build
              sudo ninja -C build install
              sudo ldconfig
            fi
          fi
          # Add libcamera development packages
          sudo apt-get install -y libcamera-dev
          # For hardware interaction - we'll try to install these but allow failures
          # since we're running in CI with CI_TEST_MODE=1
          sudo apt-get install -y liblgpio-dev || true
          sudo apt-get install -y spi-tools || true      
          
      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-ccache-${{ github.ref }}
          max-size: 1G

      - name: Configure CMake
        run: |
          cd Software/LMSourceCode/ImageProcessing
          # Create compatibility symlinks if needed by the code
          ln -sf core/rpicam_app.hpp core/libcamera_app.hpp || true
          cmake -B build -S . -G Ninja -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        env:
          CMAKE_BUILD_TYPE: Release
          PITRAC_SLOT1_CAMERA_TYPE: "auto"  # Required by gs_config.cpp

      - name: Build
        run: |
          cd Software/LMSourceCode/ImageProcessing
          ninja -C build
      
      - name: Create Test Directories
        run: |
          mkdir -p Software/LMSourceCode/ImageProcessing/test_suite
          mkdir -p Software/LMSourceCode/ImageProcessing/test_data

      - name: Run Automated Tests
        run: |
          cd Software/LMSourceCode/ImageProcessing/build
          ./gs_automated_testing
        env:
          # Configure environment variables needed for tests
          GS_TEST_SUITE_DIR: ${{ github.workspace }}/Software/LMSourceCode/ImageProcessing/test_suite
          TEST_DATA_DIR: ${{ github.workspace }}/Software/LMSourceCode/ImageProcessing/test_data
          PITRAC_SLOT1_CAMERA_TYPE: "auto"
          # Disable hardware access in CI environment
          CI_TEST_MODE: "1"
