---
name: Automated Tests

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            /var/cache/apt/archives
            ~/.cache/pip
            Software/LMSourceCode/ImageProcessing/build
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/CMakeLists.txt', 'Software/LMSourceCode/ImageProcessing/**/*.h', 'Software/LMSourceCode/ImageProcessing/**/*.hpp') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libevent-dev  
          sudo apt install -y pybind11-dev
          sudo apt -y install doxygen
          sudo apt install -y python3-graphviz  
          sudo apt install -y python3-sphinx
          sudo apt install -y python3-yaml python3-ply  
          sudo apt install -y libavdevice-dev
          sudo apt install -y qtbase5-dev libqt5core5a libqt5gui5 libqt5widgets5
          sudo apt install -y libcamera-dev libepoxy-dev libjpeg-dev libtiff5-dev libpng-dev   
          sudo apt install -y qtbase5-dev libqt5core5a libqt5gui5 libqt5widgets5
          sudo apt install libavcodec-dev libavdevice-dev libavformat-dev libswresample-dev
          
          git clone https://github.com/raspberrypi/rpicam-apps.git
          cd rpicam-apps
          meson setup build -Denable_libav=disabled -Denable_drm=enabled -Denable_egl=disabled -Denable_qt=disabled -Denable_opencv=disabled -Denable_tflite=disabled -Denable_hailo=disabled
          meson compile -C build
          sudo meson install -C build
          sudo ldconfig

      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-ccache-${{ github.ref }}
          max-size: 1G

      - name: Configure CMake
        run: |
          cd Software/LMSourceCode/ImageProcessing
          # Create compatibility symlinks if needed by the code
          ln -sf core/rpicam_app.hpp core/libcamera_app.hpp || true
          cmake -B build -S . -G Ninja -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        env:
          CMAKE_BUILD_TYPE: Release
          PITRAC_SLOT1_CAMERA_TYPE: "auto"  # Required by gs_config.cpp

      - name: Build
        run: |
          cd Software/LMSourceCode/ImageProcessing
          ninja -C build
      
      - name: Create Test Directories
        run: |
          mkdir -p Software/LMSourceCode/ImageProcessing/test_suite
          mkdir -p Software/LMSourceCode/ImageProcessing/test_data

      - name: Run Automated Tests
        run: |
          cd Software/LMSourceCode/ImageProcessing/build
          ./gs_automated_testing
        env:
          # Configure environment variables needed for tests
          GS_TEST_SUITE_DIR: ${{ github.workspace }}/Software/LMSourceCode/ImageProcessing/test_suite
          TEST_DATA_DIR: ${{ github.workspace }}/Software/LMSourceCode/ImageProcessing/test_data
          PITRAC_SLOT1_CAMERA_TYPE: "auto"
          # Disable hardware access in CI environment
          CI_TEST_MODE: "1"
