---
name: Camera Tests
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
env:
  BOOST_VERSION: 1.84.0
  BOOST_MSVC_VERSION: "14.3"
jobs:
  camera-tests:
    name: Camera Bounded Context Tests
    runs-on: windows-latest
    defaults:
      run:
        working-directory: Software/LMSourceCode/ImageProcessing/Camera
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.20"

      - name: Install boost
        uses: MarkusJx/install-boost@v2
        id: install-boost
        with:
          boost_version: ${{ env.BOOST_VERSION }}
          boost_install_dir: C:\Dev_Env\
          platform_version: 2019
          toolset: msvc

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Configure CMake
        run: >
          mkdir build

          cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE -B build -DBoost_INCLUDE_DIR=${{steps.install-boost.outputs.BOOST_ROOT}}/include -DBoost_LIBRARY_DIRS=${{steps.install-boost.outputs.BOOST_ROOT}}/lib
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

      - name: Build tests
        run: |
          cd build
          cmake --build . --config Debug
        shell: pwsh

      - name: Quick Test Validation
        run: |
          Write-Host "=== Running Direct Test Executable ==="
          ./build/tests/camera_tests.exe
        shell: pwsh      
      
      - name: Comprehensive Test Report
        run: |
          Write-Host "=== Running CTest with Detailed Reporting ==="
          cd build/tests
          
          # Run CTest with XML output (JUnit format) from the tests directory
          ctest -C Debug --verbose --output-on-failure --output-junit ./build/tests/test-results.xml
          
          # Debug: Show what files were created
          Write-Host "=== Files in tests directory after CTest ==="
          Get-ChildItem | Format-Table Name, Length
        shell: pwsh
