---
name: PiTrac CI/CD
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch: null
jobs:
  test_windows:
    name: Test on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Visual Studio tools
        uses: microsoft/setup-msbuild@v1.1
      - name: Install OpenCV
        run: |
          ./configure-windows.ps1
        shell: pwsh
      - name: Install Boost
        run: >
          choco install boost-msvc-14.3 -y

          echo "BOOST_ROOT=C:\local\boost_1_83_0" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: pwsh
      - name: Install OpenCppCoverage
        run: choco install opencppcoverage -y
        shell: pwsh
      - name: Run Tests
        run: >
          .\ci-test-integration.ps1 -IncludeBoostTests -IncludeMainTests -Coverage
          -OutputDir "$env:GITHUB_WORKSPACE\test-results"
        shell: pwsh
